#pragma once

#include <unistd.h> 
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/wait.h>
#include <sys/un.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <string>
#include <cstring>
#include <iostream>
#include <ctime>  
#include <fstream>
#include <map>
#include <chrono>
#include <thread>
#include <sstream>
#include <unordered_map>
